name: Image Build

on:
  workflow_call:
    secrets:
      gh_cr_token:
        description: 'GitHub Container Registry token'
        required: true
    inputs:
      version:
        type: string
        description: 'Image version tag'
        required: true
        default: 'latest'
      app:
        type: string
        description: 'Application name'
        required: true
      registry:
        type: string
        description: 'Container registry'
        required: true

jobs:
  build:
    name: "${{ inputs.app }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_CR_TOKEN }}
      - name: "BuildX Configuration"
        run: |
          docker buildx create --name buildxBuilder --use
          docker buildx inspect buildxBuilder --bootstrap
      - name: "${{ inputs.app }} image build"
        run: |
          cd ${{ inputs.app }}
          TAG_NAME=${{ inputs.version }}
          echo "Tag detected: $TAG_NAME"
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ${{ inputs.registry }}/${{ inputs.app }}:$TAG_NAME \
            -t ${{ inputs.registry }}/${{ inputs.app }}:latest \
            --push .
